// <auto-generated />
using System;
using API_REST.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_REST.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200511190330_IM")]
    partial class IM
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bussiness_Logic.Models.Line_Hydrocarbon", b =>
                {
                    b.Property<int>("Id_LineHydrocarbon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Diameter_Line")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("InstalationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Length_Line")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name_Line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_LineHydrocarbon");

                    b.ToTable("Line_Hydrocarbons");
                });
#pragma warning restore 612, 618
        }
    }
}
